export const events = [
    {
        title: "React Conf 2026",
        image: "/images/event1.png",
        slug: "react-conf-2026",
        location: "Henderson, Nevada",
        date: "May 14 - 15, 2026",
        time: "9:00 AM PST",
    },
    {
        title: "Google I/O 2026",
        image: "/images/event2.png",
        slug: "google-io-2026",
        location: "Mountain View, California",
        date: "May 20 - 21, 2026",
        time: "10:00 AM PST",
    },
    {
        title: "WWDC 2026",
        image: "/images/event3.png",
        slug: "wwdc-2026",
        location: "Cupertino, California",
        date: "Jun 8 - 12, 2026",
        time: "10:00 AM PDT",
    },
    {
        title: "GitHub Universe 2026",
        image: "/images/event4.png",
        slug: "github-universe-2026",
        location: "San Francisco, California",
        date: "Sep 28 - 29, 2026",
        time: "9:00 AM PDT",
    },
    {
        title: "Next.js Conf 2026",
        image: "/images/event5.png",
        slug: "nextjs-conf-2026",
        location: "Online & Austin, Texas",
        date: "Oct 14 - 15, 2026",
        time: "11:00 AM CDT",
    },
    {
        title: "Vercel Ship 2026",
        image: "/images/event6.png",
        slug: "vercel-ship-2026",
        location: "San Francisco, California",
        date: "Nov 5, 2026",
        time: "10:00 AM PST",
    },
];
